using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Linq;

namespace Recipes.SingleModelCrud
{
    /// <summary>
    /// This use case performs basic CRUD operations on a simple model without children.
    /// </summary>
    /// <typeparam name="TModel">A EmployeeClassification model or entity</typeparam>
    public abstract class SingleModelCrudTests<TModel>
        where TModel : IEmployeeClassification, new()
    {
        protected abstract ISingleModelCrudRepository<TModel> GetRepository();

        /// <summary>
        /// Create and read back a row.
        /// </summary>
        [TestMethod]
        public void CreateAndReadBack()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var echo = repository.GetByKey(newKey);
            Assert.AreEqual(newKey, echo.EmployeeClassificationKey);
            Assert.AreEqual(newRecord.EmployeeClassificationName, echo.EmployeeClassificationName);

            var search = repository.FindByName(newRecord.EmployeeClassificationName);
            Assert.AreEqual(newKey, search.EmployeeClassificationKey);
            Assert.AreEqual(newRecord.EmployeeClassificationName, search.EmployeeClassificationName);
        }

        /// <summary>
        /// Create and delete a row.
        /// </summary>
        [TestMethod]
        public void CreateAndDeleteByModel()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var echo = repository.GetByKey(newKey);

            repository.Delete(echo);

            var all = repository.GetAll();
            Assert.IsFalse(all.Any(ec => ec.EmployeeClassificationKey == newKey));
        }

        /// <summary>
        /// Create and delete a row.
        /// </summary>
        [TestMethod]
        public void CreateAndDeleteByKey()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            repository.DeleteByKey(newKey);

            var all = repository.GetAll();
            Assert.IsFalse(all.Any(ec => ec.EmployeeClassificationKey == newKey));
        }

        /// <summary>
        /// Get all rows from a table.
        /// </summary>
        [TestMethod]
        public void GetAll()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var all = repository.GetAll();
            Assert.IsNotNull(all);
            Assert.AreNotEqual(0, all.Count);
        }

        /// <summary>
        /// Get a row using a primary key.
        /// </summary>
        [TestMethod]
        public void GetByKey()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var ec1 = repository.GetByKey(1);
            var ec2 = repository.GetByKey(2);
            var ec3 = repository.GetByKey(3);

            Assert.AreEqual(1, ec1.EmployeeClassificationKey);
            Assert.AreEqual(2, ec2.EmployeeClassificationKey);
            Assert.AreEqual(3, ec3.EmployeeClassificationKey);
        }

        /// <summary>
        /// Create and update a row.
        /// </summary>
        [TestMethod]
        public void CreateAndUpdate()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000); //keys under 1000 were not generated by the database

            var echo = repository.GetByKey(newKey);
            Assert.AreEqual(newRecord.EmployeeClassificationName, echo.EmployeeClassificationName);
            echo.EmployeeClassificationName = "Updated " + DateTime.Now.Ticks;
            repository.Update(echo);

            var updated = repository.GetByKey(newKey);
            Assert.AreEqual(echo.EmployeeClassificationName, updated.EmployeeClassificationName);
        }
    }
}
