namespace Recipes.Joins;

/// <summary>
/// This scenario using a join defined on the client, but executed in the database.
/// </summary>
[TestCategory("Joins")]
public abstract class JoinsTests<TEmployeeDetail, TEmployeeSimple> : TestBase
   where TEmployeeDetail : class, IEmployeeDetail
   where TEmployeeSimple : class, IEmployeeSimple, new()
{
    [TestMethod]
    public void FindByEmployeeClassificationKey()
    {
        var repository = GetScenario();

        var employeeClassification = repository.GetClassification(3);
        Assert.IsNotNull(employeeClassification);

        var newRecord = new TEmployeeSimple
        {
            FirstName = "Test",
            MiddleName = "A",
            LastName = "Person " + DateTime.Now.Ticks,
            EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
        };
        var newKey = repository.Create(newRecord);
        Assert.IsGreaterThanOrEqualTo(1000, newKey, "keys under 1000 were not generated by the database");

        var list = repository.FindByEmployeeClassificationKey(employeeClassification!.EmployeeClassificationKey);
        var echo = list.Single(x => x.EmployeeKey == newKey);
        Assert.IsNotNull(echo);
        Assert.AreEqual(newKey, echo.EmployeeKey);
        Assert.AreEqual(newRecord.FirstName, echo.FirstName);
        Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
        Assert.AreEqual(newRecord.LastName, echo.LastName);
        Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
        Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
        Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
        Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);
    }

    [TestMethod]
    public void FindByName()
    {
        var repository = GetScenario();

        var employeeClassification = repository.GetClassification(3);
        Assert.IsNotNull(employeeClassification);

        var newRecord = new TEmployeeSimple
        {
            FirstName = "Test",
            MiddleName = "A",
            LastName = "Person " + DateTime.Now.Ticks,
            EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
        };
        var newKey = repository.Create(newRecord);
        Assert.IsGreaterThanOrEqualTo(1000, newKey, "keys under 1000 were not generated by the database");

        var list = repository.FindByLastName(newRecord.LastName);
        var echo = list.Single();
        Assert.IsNotNull(echo);
        Assert.AreEqual(newKey, echo.EmployeeKey);
        Assert.AreEqual(newRecord.FirstName, echo.FirstName);
        Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
        Assert.AreEqual(newRecord.LastName, echo.LastName);
        Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
        Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
        Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
        Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);
    }

    [TestMethod]
    public void GetByEmployeeKey()
    {
        var repository = GetScenario();

        var employeeClassification = repository.GetClassification(3);
        Assert.IsNotNull(employeeClassification);

        var newRecord = new TEmployeeSimple
        {
            FirstName = "Test",
            MiddleName = "A",
            LastName = "Person " + DateTime.Now.Ticks,
            EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
        };
        var newKey = repository.Create(newRecord);
        Assert.IsGreaterThanOrEqualTo(1000, newKey, "keys under 1000 were not generated by the database");

        var echo = repository.GetByEmployeeKey(newKey);
        Assert.IsNotNull(echo);
        Assert.AreEqual(newKey, echo!.EmployeeKey);
        Assert.AreEqual(newRecord.FirstName, echo.FirstName);
        Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
        Assert.AreEqual(newRecord.LastName, echo.LastName);
        Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
        Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
        Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
        Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);
    }

    protected abstract IJoinsScenario<TEmployeeDetail, TEmployeeSimple> GetScenario();
}