using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Recipes.SingleModelCrudAsync
{
    /// <summary>
    /// This use case performs basic CRUD operations on a simple model without children.
    /// </summary>
    /// <typeparam name="TModel">A EmployeeClassification model or entity</typeparam>
    public abstract class SingleModelCrudAsyncTests<TModel>
        where TModel : IEmployeeClassification, new()
    {
        protected abstract ISingleModelCrudAsyncRepository<TModel> GetRepository();

        /// <summary>
        /// Create and read back a row.
        /// </summary>
        [TestMethod]
        public async Task CreateAndReadBackAsync()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = await repository.CreateAsync(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var echo = await repository.GetByKeyAsync(newKey);
            Assert.AreEqual(newKey, echo.EmployeeClassificationKey);
            Assert.AreEqual(newRecord.EmployeeClassificationName, echo.EmployeeClassificationName);

            var search = await repository.FindByNameAsync(newRecord.EmployeeClassificationName);
            Assert.AreEqual(newKey, search.EmployeeClassificationKey);
            Assert.AreEqual(newRecord.EmployeeClassificationName, search.EmployeeClassificationName);
        }

        /// <summary>
        /// Create and delete a row.
        /// </summary>
        [TestMethod]
        public async Task CreateAndDeleteByModelAsync()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = await repository.CreateAsync(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var echo = await repository.GetByKeyAsync(newKey);

            await repository.DeleteAsync(echo);

            var all = await repository.GetAllAsync();
            Assert.IsFalse(all.Any(ec => ec.EmployeeClassificationKey == newKey));
        }

        /// <summary>
        /// Create and delete a row.
        /// </summary>
        [TestMethod]
        public async Task CreateAndDeleteByKeyAsync()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = await repository.CreateAsync(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            await repository.DeleteByKeyAsync(newKey);

            var all = await repository.GetAllAsync();
            Assert.IsFalse(all.Any(ec => ec.EmployeeClassificationKey == newKey));
        }

        /// <summary>
        /// Get all rows from a table.
        /// </summary>
        [TestMethod]
        public async Task GetAllAsync()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var all = await repository.GetAllAsync();
            Assert.IsNotNull(all);
            Assert.AreNotEqual(0, all.Count);
        }

        /// <summary>
        /// Get a row using a primary key.
        /// </summary>
        [TestMethod]
        public async Task GetByKeyAsync()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var ec1 = await repository.GetByKeyAsync(1);
            var ec2 = await repository.GetByKeyAsync(2);
            var ec3 = await repository.GetByKeyAsync(3);

            Assert.AreEqual(1, ec1.EmployeeClassificationKey);
            Assert.AreEqual(2, ec2.EmployeeClassificationKey);
            Assert.AreEqual(3, ec3.EmployeeClassificationKey);
        }

        /// <summary>
        /// Create and update a row.
        /// </summary>
        [TestMethod]
        public async Task CreateAndUpdateAsync()
        {
            var repository = GetRepository();
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = await repository.CreateAsync(newRecord);
            Assert.IsTrue(newKey >= 1000); //keys under 1000 were not generated by the database

            var echo = await repository.GetByKeyAsync(newKey);
            Assert.AreEqual(newRecord.EmployeeClassificationName, echo.EmployeeClassificationName);
            echo.EmployeeClassificationName = "Updated " + DateTime.Now.Ticks;
            await repository.UpdateAsync(echo);

            var updated = await repository.GetByKeyAsync(newKey);
            Assert.AreEqual(echo.EmployeeClassificationName, updated.EmployeeClassificationName);
        }
    }
}
