//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace LLBLGenPro.OrmCookbook
{
	/// <summary>Index enum to fast-access Typed View EntityFields in the IEntityFields collection for the typed view : DepartmentDetail.</summary>
	public enum DepartmentDetailFieldIndex
	{
		///<summary>DepartmentKey</summary>
		DepartmentKey,
		///<summary>DepartmentName</summary>
		DepartmentName,
		///<summary>DivisionKey</summary>
		DivisionKey,
		///<summary>DivisionName</summary>
		DivisionName,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access Typed View EntityFields in the IEntityFields collection for the typed view : EmployeeDetail.</summary>
	public enum EmployeeDetailFieldIndex
	{
		///<summary>EmployeeKey</summary>
		EmployeeKey,
		///<summary>FirstName</summary>
		FirstName,
		///<summary>MiddleName</summary>
		MiddleName,
		///<summary>LastName</summary>
		LastName,
		///<summary>Title</summary>
		Title,
		///<summary>OfficePhone</summary>
		OfficePhone,
		///<summary>CellPhone</summary>
		CellPhone,
		///<summary>EmployeeClassificationKey</summary>
		EmployeeClassificationKey,
		///<summary>EmployeeClassificationName</summary>
		EmployeeClassificationName,
		///<summary>IsExempt</summary>
		IsExempt,
		///<summary>IsEmployee</summary>
		IsEmployee,
		/// <summary></summary>
		AmountOfFields
	}


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Department</summary>
		DepartmentEntity,
		///<summary>Division</summary>
		DivisionEntity,
		///<summary>Employee</summary>
		EmployeeEntity,
		///<summary>EmployeeClassification</summary>
		EmployeeClassificationEntity,
		///<summary>Product</summary>
		ProductEntity,
		///<summary>ProductLine</summary>
		ProductLineEntity
	}

	/// <summary>Enum definition for all the typed view types defined in this namespace. Used by the entityfields factory.</summary>
	public enum TypedViewType
	{
		///<summary>DepartmentDetail</summary>
		DepartmentDetailTypedView,
		///<summary>EmployeeDetail</summary>
		EmployeeDetailTypedView
	}


	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

