using Microsoft.EntityFrameworkCore;
using System;

namespace Recipes.EntityFrameworkCore.Entities
{
    partial class OrmCookbookContext : DbContext
    {
#nullable disable //Assume that the DbContext constructor will populate these properties
        public virtual DbSet<EmployeeClassificationKeyHolder> EmployeeClassificationKeyHolder { get; set; }
        public virtual DbSet<EmployeeClassificationWithCount> EmployeeClassificationWithCount { get; set; }
#nullable enable

        static void RegisterEntitiesForStoredProcedures(ModelBuilder modelBuilder)
        {
            //Output types for stored procedures. Not generated by Scaffold-DbContext

            modelBuilder.Entity<EmployeeClassificationWithCount>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.EmployeeClassificationName).IsUnicode(false);
            });

            modelBuilder.Entity<EmployeeClassificationKeyHolder>(entity =>
            {
                entity.HasNoKey();
            });
        }
    }
}
