using Recipes.Models;
using Recipes.Repositories;
using System;
using System.Linq;
using Xunit;

namespace Recipes.UseCases
{

    /// <summary>
    /// This set of use cases demonstrates how to perform CRUD operations on a single model.
    /// </summary>
    public abstract class SingleModelCrud<TModel>
        where TModel : IEmployeeClassification, new()
    {

        [Fact]
        public abstract void CreateAndReadBack();

        public void CreateAndReadBack(IEmployeeClassificationRepository<TModel> repository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.True(newKey >= 1000); //keys under 1000 were not generated by the database

            var echo = repository.GetByKey(newKey);
            Assert.Equal(newKey, echo.EmployeeClassificationKey);
            Assert.Equal(newRecord.EmployeeClassificationName, echo.EmployeeClassificationName);


            var search = repository.FindByName(newRecord.EmployeeClassificationName);
            Assert.Equal(newKey, search.EmployeeClassificationKey);
            Assert.Equal(newRecord.EmployeeClassificationName, search.EmployeeClassificationName);
        }

        [Fact]
        public abstract void CreateAndDelete();

        public void CreateAndDelete(IEmployeeClassificationRepository<TModel> repository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.True(newKey >= 1000); //keys under 1000 were not generated by the database

            repository.Delete(newKey);

            var all = repository.GetAll();
            Assert.False(all.Any(ec => ec.EmployeeClassificationKey == newKey));
        }

        [Fact]
        public abstract void GetAll();

        public void GetAll(IEmployeeClassificationRepository<TModel> repository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var all = repository.GetAll();
            Assert.NotNull(all);
            Assert.NotEmpty(all);
        }

        [Fact]
        public abstract void GetByKey();

        public void GetByKey(IEmployeeClassificationRepository<TModel> repository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");


            var ec1 = repository.GetByKey(1);
            var ec2 = repository.GetByKey(2);
            var ec3 = repository.GetByKey(3);

            Assert.Equal(1, ec1.EmployeeClassificationKey);
            Assert.Equal(2, ec2.EmployeeClassificationKey);
            Assert.Equal(3, ec3.EmployeeClassificationKey);

        }

        [Fact]
        public abstract void CreateAndUpdate();

        public void CreateAndUpdate(IEmployeeClassificationRepository<TModel> repository)
        {
            if (repository == null)
                throw new ArgumentNullException("repository", "repository is null.");

            var newRecord = new TModel();
            newRecord.EmployeeClassificationName = "Test " + DateTime.Now.Ticks;
            var newKey = repository.Create(newRecord);
            Assert.True(newKey >= 1000); //keys under 1000 were not generated by the database

            var echo = repository.GetByKey(newKey);
            Assert.Equal(newRecord.EmployeeClassificationName, echo.EmployeeClassificationName);
            echo.EmployeeClassificationName = "Updated " + DateTime.Now.Ticks;
            repository.Update(echo);

            var updated = repository.GetByKey(newKey);
            Assert.Equal(echo.EmployeeClassificationName, updated.EmployeeClassificationName);


        }
    }
}
