//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGenPro.OrmCookbook.HelperClasses
{
	/// <summary>Field Creation Class for entity DepartmentEntity</summary>
	public partial class DepartmentFields
	{
		/// <summary>Creates a new DepartmentEntity.DepartmentKey field instance</summary>
		public static EntityField2 DepartmentKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.DepartmentKey); }}
		/// <summary>Creates a new DepartmentEntity.DepartmentName field instance</summary>
		public static EntityField2 DepartmentName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.DepartmentName); }}
		/// <summary>Creates a new DepartmentEntity.DivisionKey field instance</summary>
		public static EntityField2 DivisionKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.DivisionKey); }}
	}

	/// <summary>Field Creation Class for entity DivisionEntity</summary>
	public partial class DivisionFields
	{
		/// <summary>Creates a new DivisionEntity.DivisionKey field instance</summary>
		public static EntityField2 DivisionKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DivisionFieldIndex.DivisionKey); }}
		/// <summary>Creates a new DivisionEntity.DivisionName field instance</summary>
		public static EntityField2 DivisionName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DivisionFieldIndex.DivisionName); }}
	}

	/// <summary>Field Creation Class for entity EmployeeEntity</summary>
	public partial class EmployeeFields
	{
		/// <summary>Creates a new EmployeeEntity.CellPhone field instance</summary>
		public static EntityField2 CellPhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.CellPhone); }}
		/// <summary>Creates a new EmployeeEntity.EmployeeClassificationKey field instance</summary>
		public static EntityField2 EmployeeClassificationKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.EmployeeClassificationKey); }}
		/// <summary>Creates a new EmployeeEntity.EmployeeKey field instance</summary>
		public static EntityField2 EmployeeKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.EmployeeKey); }}
		/// <summary>Creates a new EmployeeEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.FirstName); }}
		/// <summary>Creates a new EmployeeEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.LastName); }}
		/// <summary>Creates a new EmployeeEntity.MiddleName field instance</summary>
		public static EntityField2 MiddleName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.MiddleName); }}
		/// <summary>Creates a new EmployeeEntity.OfficePhone field instance</summary>
		public static EntityField2 OfficePhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.OfficePhone); }}
		/// <summary>Creates a new EmployeeEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Title); }}
	}

	/// <summary>Field Creation Class for entity EmployeeClassificationEntity</summary>
	public partial class EmployeeClassificationFields
	{
		/// <summary>Creates a new EmployeeClassificationEntity.EmployeeClassificationKey field instance</summary>
		public static EntityField2 EmployeeClassificationKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeClassificationFieldIndex.EmployeeClassificationKey); }}
		/// <summary>Creates a new EmployeeClassificationEntity.EmployeeClassificationName field instance</summary>
		public static EntityField2 EmployeeClassificationName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeClassificationFieldIndex.EmployeeClassificationName); }}
		/// <summary>Creates a new EmployeeClassificationEntity.IsEmployee field instance</summary>
		public static EntityField2 IsEmployee { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeClassificationFieldIndex.IsEmployee); }}
		/// <summary>Creates a new EmployeeClassificationEntity.IsExempt field instance</summary>
		public static EntityField2 IsExempt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeClassificationFieldIndex.IsExempt); }}
	}

	/// <summary>Field Creation Class for entity EmployeeDetailEntity</summary>
	public partial class EmployeeDetailFields
	{
		/// <summary>Creates a new EmployeeDetailEntity.CellPhone field instance</summary>
		public static EntityField2 CellPhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.CellPhone); }}
		/// <summary>Creates a new EmployeeDetailEntity.EmployeeClassificationKey field instance</summary>
		public static EntityField2 EmployeeClassificationKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.EmployeeClassificationKey); }}
		/// <summary>Creates a new EmployeeDetailEntity.EmployeeClassificationName field instance</summary>
		public static EntityField2 EmployeeClassificationName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.EmployeeClassificationName); }}
		/// <summary>Creates a new EmployeeDetailEntity.EmployeeKey field instance</summary>
		public static EntityField2 EmployeeKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.EmployeeKey); }}
		/// <summary>Creates a new EmployeeDetailEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.FirstName); }}
		/// <summary>Creates a new EmployeeDetailEntity.IsEmployee field instance</summary>
		public static EntityField2 IsEmployee { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.IsEmployee); }}
		/// <summary>Creates a new EmployeeDetailEntity.IsExempt field instance</summary>
		public static EntityField2 IsExempt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.IsExempt); }}
		/// <summary>Creates a new EmployeeDetailEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.LastName); }}
		/// <summary>Creates a new EmployeeDetailEntity.MiddleName field instance</summary>
		public static EntityField2 MiddleName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.MiddleName); }}
		/// <summary>Creates a new EmployeeDetailEntity.OfficePhone field instance</summary>
		public static EntityField2 OfficePhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.OfficePhone); }}
		/// <summary>Creates a new EmployeeDetailEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeDetailFieldIndex.Title); }}
	}

	/// <summary>Field Creation Class for entity ProductEntity</summary>
	public partial class ProductFields
	{
		/// <summary>Creates a new ProductEntity.ProductKey field instance</summary>
		public static EntityField2 ProductKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.ProductKey); }}
		/// <summary>Creates a new ProductEntity.ProductLineKey field instance</summary>
		public static EntityField2 ProductLineKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.ProductLineKey); }}
		/// <summary>Creates a new ProductEntity.ProductName field instance</summary>
		public static EntityField2 ProductName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.ProductName); }}
		/// <summary>Creates a new ProductEntity.ProductWeight field instance</summary>
		public static EntityField2 ProductWeight { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.ProductWeight); }}
		/// <summary>Creates a new ProductEntity.ShippingWeight field instance</summary>
		public static EntityField2 ShippingWeight { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.ShippingWeight); }}
	}

	/// <summary>Field Creation Class for entity ProductLineEntity</summary>
	public partial class ProductLineFields
	{
		/// <summary>Creates a new ProductLineEntity.ProductLineKey field instance</summary>
		public static EntityField2 ProductLineKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductLineFieldIndex.ProductLineKey); }}
		/// <summary>Creates a new ProductLineEntity.ProductLineName field instance</summary>
		public static EntityField2 ProductLineName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductLineFieldIndex.ProductLineName); }}
	}
	

	/// <summary>Field Creation Class for typedview DepartmentDetailTypedView</summary>
	public partial class DepartmentDetailFields
	{
		/// <summary>Creates a new DepartmentDetailTypedView.DepartmentKey field instance</summary>
		public static EntityField2 DepartmentKey	{ get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentDetailFieldIndex.DepartmentKey); } }
		/// <summary>Creates a new DepartmentDetailTypedView.DepartmentName field instance</summary>
		public static EntityField2 DepartmentName	{ get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentDetailFieldIndex.DepartmentName); } }
		/// <summary>Creates a new DepartmentDetailTypedView.DivisionKey field instance</summary>
		public static EntityField2 DivisionKey	{ get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentDetailFieldIndex.DivisionKey); } }
		/// <summary>Creates a new DepartmentDetailTypedView.DivisionName field instance</summary>
		public static EntityField2 DivisionName	{ get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentDetailFieldIndex.DivisionName); } }
	}
}