//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using LLBLGenPro.OrmCookbook.FactoryClasses;
using LLBLGenPro.OrmCookbook.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGenPro.OrmCookbook.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitDepartmentEntityInfo();
			InitDivisionEntityInfo();
			InitEmployeeEntityInfo();
			InitEmployeeClassificationEntityInfo();
			InitDepartmentDetailTypedViewInfo();
			InitEmployeeDetailTypedViewInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits DepartmentEntity's info objects</summary>
		private void InitDepartmentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(DepartmentFieldIndex), "DepartmentEntity");
			this.AddElementFieldInfo("DepartmentEntity", "DepartmentKey", typeof(System.Int32), true, false, true, false,  (int)DepartmentFieldIndex.DepartmentKey, 0, 0, 10);
			this.AddElementFieldInfo("DepartmentEntity", "DepartmentName", typeof(System.String), false, false, false, false,  (int)DepartmentFieldIndex.DepartmentName, 30, 0, 0);
			this.AddElementFieldInfo("DepartmentEntity", "DivisionKey", typeof(System.Int32), false, true, false, false,  (int)DepartmentFieldIndex.DivisionKey, 0, 0, 10);
		}

		/// <summary>Inits DivisionEntity's info objects</summary>
		private void InitDivisionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(DivisionFieldIndex), "DivisionEntity");
			this.AddElementFieldInfo("DivisionEntity", "DivisionKey", typeof(System.Int32), true, false, true, false,  (int)DivisionFieldIndex.DivisionKey, 0, 0, 10);
			this.AddElementFieldInfo("DivisionEntity", "DivisionName", typeof(System.String), false, false, false, false,  (int)DivisionFieldIndex.DivisionName, 30, 0, 0);
		}

		/// <summary>Inits EmployeeEntity's info objects</summary>
		private void InitEmployeeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(EmployeeFieldIndex), "EmployeeEntity");
			this.AddElementFieldInfo("EmployeeEntity", "CellPhone", typeof(System.String), false, false, false, true,  (int)EmployeeFieldIndex.CellPhone, 15, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "EmployeeClassificationKey", typeof(System.Int32), false, true, false, false,  (int)EmployeeFieldIndex.EmployeeClassificationKey, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeEntity", "EmployeeKey", typeof(System.Int32), true, false, true, false,  (int)EmployeeFieldIndex.EmployeeKey, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)EmployeeFieldIndex.FirstName, 50, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "LastName", typeof(System.String), false, false, false, false,  (int)EmployeeFieldIndex.LastName, 50, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "MiddleName", typeof(System.String), false, false, false, true,  (int)EmployeeFieldIndex.MiddleName, 50, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "OfficePhone", typeof(System.String), false, false, false, true,  (int)EmployeeFieldIndex.OfficePhone, 15, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "Title", typeof(System.String), false, false, false, true,  (int)EmployeeFieldIndex.Title, 100, 0, 0);
		}

		/// <summary>Inits EmployeeClassificationEntity's info objects</summary>
		private void InitEmployeeClassificationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(EmployeeClassificationFieldIndex), "EmployeeClassificationEntity");
			this.AddElementFieldInfo("EmployeeClassificationEntity", "EmployeeClassificationKey", typeof(System.Int32), true, false, true, false,  (int)EmployeeClassificationFieldIndex.EmployeeClassificationKey, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeClassificationEntity", "EmployeeClassificationName", typeof(System.String), false, false, false, false,  (int)EmployeeClassificationFieldIndex.EmployeeClassificationName, 30, 0, 0);
			this.AddElementFieldInfo("EmployeeClassificationEntity", "IsEmployee", typeof(System.Boolean), false, false, false, false,  (int)EmployeeClassificationFieldIndex.IsEmployee, 0, 0, 0);
			this.AddElementFieldInfo("EmployeeClassificationEntity", "IsExempt", typeof(System.Boolean), false, false, false, false,  (int)EmployeeClassificationFieldIndex.IsExempt, 0, 0, 0);
		}

		/// <summary>Inits DepartmentDetailView's info objects</summary>
		private void InitDepartmentDetailTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(DepartmentDetailFieldIndex), "DepartmentDetailTypedView");
			this.AddElementFieldInfo("DepartmentDetailTypedView", "DepartmentKey", typeof(System.Int32), false, false, true, false, (int)DepartmentDetailFieldIndex.DepartmentKey, 0, 0, 10);
			this.AddElementFieldInfo("DepartmentDetailTypedView", "DepartmentName", typeof(System.String), false, false, true, false, (int)DepartmentDetailFieldIndex.DepartmentName, 30, 0, 0);
			this.AddElementFieldInfo("DepartmentDetailTypedView", "DivisionKey", typeof(System.Int32), false, false, true, false, (int)DepartmentDetailFieldIndex.DivisionKey, 0, 0, 10);
			this.AddElementFieldInfo("DepartmentDetailTypedView", "DivisionName", typeof(System.String), false, false, true, false, (int)DepartmentDetailFieldIndex.DivisionName, 30, 0, 0);
		}

		/// <summary>Inits EmployeeDetailView's info objects</summary>
		private void InitEmployeeDetailTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(EmployeeDetailFieldIndex), "EmployeeDetailTypedView");
			this.AddElementFieldInfo("EmployeeDetailTypedView", "EmployeeKey", typeof(System.Int32), false, false, true, false, (int)EmployeeDetailFieldIndex.EmployeeKey, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "FirstName", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.FirstName, 50, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "MiddleName", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.MiddleName, 50, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "LastName", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.LastName, 50, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "Title", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.Title, 100, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "OfficePhone", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.OfficePhone, 15, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "CellPhone", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.CellPhone, 15, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "EmployeeClassificationKey", typeof(System.Int32), false, false, true, false, (int)EmployeeDetailFieldIndex.EmployeeClassificationKey, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "EmployeeClassificationName", typeof(System.String), false, false, true, false, (int)EmployeeDetailFieldIndex.EmployeeClassificationName, 30, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "IsExempt", typeof(System.Boolean), false, false, true, false, (int)EmployeeDetailFieldIndex.IsExempt, 0, 0, 0);
			this.AddElementFieldInfo("EmployeeDetailTypedView", "IsEmployee", typeof(System.Boolean), false, false, true, false, (int)EmployeeDetailFieldIndex.IsEmployee, 0, 0, 0);
		}
	}
}