using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Recipes.MultipleCrud
{
    /// <summary>
    /// This scenario reads from a view.
    /// </summary>
    [TestCategory("MultipleCrud")]
    public abstract class MultipleCrudTests<TEmployeeSimple> : TestBase
       where TEmployeeSimple : class, IEmployeeSimple, new()
    {
        const int RowCount = 100;

        [TestMethod]
        public void DeleteBatch()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            var echoes = repostory.InsertBatchReturnRows(originals);

            repostory.DeleteBatch(echoes);

            var actuals = repostory.FindByLastName(batchKey);

            Assert.AreEqual(0, actuals.Count);
        }

        [TestMethod]
        public void DeleteBatchByKey()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            var keys = repostory.InsertBatchReturnKeys(originals);

            repostory.DeleteBatchByKey(keys);
            var actuals = repostory.FindByLastName(batchKey);

            Assert.AreEqual(0, actuals.Count);
        }

        [TestMethod]
        public void InsertBatch()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            repostory.InsertBatch(originals);

            var actuals = repostory.FindByLastName(batchKey);

            CompareLists(originals, actuals);
        }

        [TestMethod]
        public void InsertBatchReturnKeys()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            var keys = repostory.InsertBatchReturnKeys(originals);

            var actuals = repostory.FindByLastName(batchKey);

            foreach (var key in keys)
                Assert.IsTrue(actuals.Any(x => x.EmployeeKey == key));

            CompareLists(originals, actuals);
        }

        [TestMethod]
        public void InsertBatchReturnRows()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            var actuals = repostory.InsertBatchReturnRows(originals);

            CompareLists(originals, actuals);
        }

        [TestMethod]
        public void InsertBatchWithUpdate()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            repostory.InsertBatchWithRefresh(originals);

            foreach (var original in originals)
                Assert.IsTrue(original.EmployeeKey >= 1000, "keys under 1000 were not generated by the database");
        }

        [TestMethod]
        public void UpdateBatch()
        {
            var repostory = GetScenario();

            var batchKey = Guid.NewGuid().ToString();
            var originals = BuildEmployees(RowCount, batchKey);
            var actuals = repostory.InsertBatchReturnRows(originals);

            CompareLists(originals, actuals);

            foreach (var item in actuals)
                item.FirstName = item.FirstName!.Replace("Test", "Updated ");

            repostory.UpdateBatch(actuals);
            var updated = repostory.FindByLastName(batchKey);

            CompareLists(actuals, updated);
        }

        protected abstract IMultipleCrudScenario<TEmployeeSimple> GetScenario();

        static IList<TEmployeeSimple> BuildEmployees(int count, string batchKey)
        {
            var result = new List<TEmployeeSimple>();
            for (var i = 0; i < count; i++)
            {
                result.Add(new TEmployeeSimple
                {
                    FirstName = "Test " + (i % 3),
                    MiddleName = "A" + i,
                    LastName = batchKey,
                    EmployeeClassificationKey = (i % 7) + 1
                });
            }
            return result;
        }

        private static void CompareLists(IList<TEmployeeSimple> originals, IList<TEmployeeSimple> actuals)
        {
            Assert.AreEqual(originals.Count, actuals.Count, "Wrong number of rows created or returned");
            foreach (var original in originals)
            {
                var actual = actuals.Single(x => x.MiddleName == original.MiddleName);
                Assert.IsTrue(actual.EmployeeKey >= 1000, "keys under 1000 were not generated by the database");
                Assert.AreEqual(original.FirstName, actual.FirstName);
                //Assert.AreEqual(original.MiddleName, actual.MiddleName);
                Assert.AreEqual(original.LastName, actual.LastName);
                Assert.AreEqual(original.EmployeeClassificationKey, actual.EmployeeClassificationKey);
            }
        }
    }
}
