using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Linq;

namespace Recipes.Joins
{
    /// <summary>
    /// This use case reads from a view.
    /// </summary>
    [TestCategory("Joins")]
    public abstract class JoinsTests<TEmployeeDetail, TEmployeeSimple> : TestBase
       where TEmployeeDetail : class, IEmployeeDetail
       where TEmployeeSimple : class, IEmployeeSimple, new()
    {
        protected abstract IJoinsRepository<TEmployeeDetail, TEmployeeSimple> GetRepository();

        [TestMethod]
        public void GetByEmployeeKey()
        {
            var repository = GetRepository();

            var employeeClassification = repository.GetClassification(3);
            Assert.IsNotNull(employeeClassification);

            var newRecord = new TEmployeeSimple
            {
                FirstName = "Test",
                MiddleName = "A",
                LastName = "Person " + DateTime.Now.Ticks,
                EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
            };
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var echo = repository.GetByEmployeeKey(newKey);
            Assert.IsNotNull(echo);
            Assert.AreEqual(newKey, echo!.EmployeeKey);
            Assert.AreEqual(newRecord.FirstName, echo.FirstName);
            Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
            Assert.AreEqual(newRecord.LastName, echo.LastName);
            Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
            Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
            Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
            Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);
        }

        [TestMethod]
        public void FindByEmployeeClassificationKey()
        {
            var repository = GetRepository();

            var employeeClassification = repository.GetClassification(3);
            Assert.IsNotNull(employeeClassification);

            var newRecord = new TEmployeeSimple
            {
                FirstName = "Test",
                MiddleName = "A",
                LastName = "Person " + DateTime.Now.Ticks,
                EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
            };
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var list = repository.FindByEmployeeClassificationKey(employeeClassification!.EmployeeClassificationKey);
            var echo = list.Single(x => x.EmployeeKey == newKey);
            Assert.IsNotNull(echo);
            Assert.AreEqual(newKey, echo.EmployeeKey);
            Assert.AreEqual(newRecord.FirstName, echo.FirstName);
            Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
            Assert.AreEqual(newRecord.LastName, echo.LastName);
            Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
            Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
            Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
            Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);
        }

        [TestMethod]
        public void FindByName()
        {
            var repository = GetRepository();

            var employeeClassification = repository.GetClassification(3);
            Assert.IsNotNull(employeeClassification);

            var newRecord = new TEmployeeSimple
            {
                FirstName = "Test",
                MiddleName = "A",
                LastName = "Person " + DateTime.Now.Ticks,
                EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
            };
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var list = repository.FindByLastName(newRecord.LastName);
            var echo = list.Single();
            Assert.IsNotNull(echo);
            Assert.AreEqual(newKey, echo.EmployeeKey);
            Assert.AreEqual(newRecord.FirstName, echo.FirstName);
            Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
            Assert.AreEqual(newRecord.LastName, echo.LastName);
            Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
            Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
            Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
            Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);
        }

        [TestMethod]
        public void GetAll()
        {
            var repository = GetRepository();

            //Ensure at least one record exists
            var employeeClassification = repository.GetClassification(3);
            Assert.IsNotNull(employeeClassification);

            var newRecord = new TEmployeeSimple
            {
                FirstName = "Test",
                MiddleName = "A",
                LastName = "Person " + DateTime.Now.Ticks,
                EmployeeClassificationKey = employeeClassification!.EmployeeClassificationKey
            };
            var newKey = repository.Create(newRecord);
            Assert.IsTrue(newKey >= 1000, "keys under 1000 were not generated by the database");

            var list = repository.GetAll();
            Assert.IsNotNull(list);

            var echo = list.Single(x => x.EmployeeKey == newKey);
            Assert.IsNotNull(echo);
            Assert.AreEqual(newKey, echo.EmployeeKey);
            Assert.AreEqual(newRecord.FirstName, echo.FirstName);
            Assert.AreEqual(newRecord.MiddleName, echo.MiddleName);
            Assert.AreEqual(newRecord.LastName, echo.LastName);
            Assert.AreEqual(newRecord.EmployeeClassificationKey, echo.EmployeeClassificationKey);
            Assert.AreEqual(employeeClassification.EmployeeClassificationName, echo.EmployeeClassificationName);
            Assert.AreEqual(employeeClassification.IsEmployee, echo.IsEmployee);
            Assert.AreEqual(employeeClassification.IsExempt, echo.IsExempt);

            foreach (var item in list)
            {
                Assert.IsTrue(0 < item.EmployeeKey);
                Assert.IsTrue(0 < item.EmployeeClassificationKey);
                Assert.IsNotNull(item.EmployeeClassificationName);
                Assert.IsNotNull(item.FirstName);
                Assert.IsNotNull(item.LastName);
            }
        }
    }
}
