//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace LLBLGenPro.OrmCookbook.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'DepartmentDetail'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="LLBLGenPro.OrmCookbook.FactoryClasses.QueryFactory.DepartmentDetail"/>. </remarks>
	[Serializable]
	public partial class DepartmentDetailRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="DepartmentDetailRow"/> class.</summary>
		public DepartmentDetailRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the DepartmentKey field.</summary>
		public System.Int32 DepartmentKey { get; set; }
		/// <summary>Gets or sets the DepartmentName field.</summary>
		public System.String DepartmentName { get; set; }
		/// <summary>Gets or sets the DivisionKey field.</summary>
		public System.Int32 DivisionKey { get; set; }
		/// <summary>Gets or sets the DivisionName field.</summary>
		public System.String DivisionName { get; set; }
	}
}

